# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-18 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('crew', models.TextField(null=True)),
                ('director', models.CharField(blank=True, max_length=250)),
                ('year', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Star_cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='movies',
            name='cast',
            field=models.ForeignKey(db_column='cast_name', on_delete=django.db.models.deletion.CASCADE, to='top200.Star_cast'),
        ),
    ]
