# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-18 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('top200', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.ForeignKey(db_column='director', on_delete=django.db.models.deletion.CASCADE, to='top200.Director'),
        ),
    ]
